### ISSUE TITLE
[検証] ターゲットノード切り替えでタスク乱立してる処理はdelegate_toでなんとかならないかな

### ISSUE THREAD

**Issue by zaki-lknr** [zaki-lknr/initialize-kubeadm-ansible#28]
- [x] ノード間のssh鍵交換とか
- [x] CNIのデプロイ
  - [x] flannel
  - [x] calico
  - [x] readyのwait
- [ ] ノード追加時のトークン作成とか
  - [ ] master追加
  - [ ] worker追加

**Comment by zaki-lknr** [comment]
targethostが`all`のタスクで`delegate_to: localhost`とすると、`all`のグループノードの回数分`localhsot`で実行されるっぽい。

# inventory

```ini
[master]
master02 ansible_host=192.168.0.122

[worker]
worker03 ansible_host=192.168.0.127
worker04 ansible_host=192.168.0.128
```

# role

```yaml
- name: create directory for ssh keypair
  file:
    path: "{{ lookup('env','HOME') }}/.ssh/"
    state: directory
    mode: 0700
  delegate_to: localhost
```

# 実行結果

```
TASK [configure_ssh : create directory for ssh keypair] ********
changed: [worker04 -> localhost]
ok: [worker03 -> localhost]
ok: [master02 -> localhost]
```

---

`delegate_to`の対象が1ノードで実行が1回だけ行われれば良いのであれば`run_once`がある

```yaml
- name: create directory for ssh keypair
  file:
    path: "{{ lookup('env','HOME') }}/.ssh/"
    state: directory
    mode: 0700
  delegate_to: localhost
  run_once: true
```

これで実行回数が1回になった

```
TASK [configure_ssh : create directory for ssh keypair] *************
changed: [worker03 -> localhost]
```

**Comment by zaki-lknr** [comment]
# 特定グループを対象に実行

`delegate_to`に指定するのはホスト名。ノードグループ名ではない。

```yaml
- name: publickey copy to target-nodes
  authorized_key:
    user: "{{ ansible_env.USER }}"
    key: "{{ lookup('file', lookup('env', 'HOME') + '/.ssh/id_rsa.pub' )}}"
  delegate_to: worker
```

これだとworkerノードグループ(worker03, worker04)でなく、workerというホスト名にアクセスにする(名前解決でエラーか、実際にアクセスできればworkerというホストで実行)

```
TASK [configure_ssh : publickey copy to target-nodes] ************
fatal: [worker03]: UNREACHABLE! => changed=false 
  msg: 'Failed to connect to the host via ssh: ssh: Could not resolve hostname worker: Name or service not known'
  unreachable: true
fatal: [worker04]: UNREACHABLE! => changed=false 
  msg: 'Failed to connect to the host via ssh: ssh: Could not resolve hostname worker: Name or service not known'
  unreachable: true
fatal: [master02]: UNREACHABLE! => changed=false 
  msg: 'Failed to connect to the host via ssh: ssh: Could not resolve hostname worker: Name or service not known'
  unreachable: true
```

---

`loop`使えばOK

```yaml
- name: publickey copy to target-nodes
  authorized_key:
    user: "{{ ansible_env.USER }}"
    key: "{{ lookup('file', lookup('env', 'HOME') + '/.ssh/id_rsa.pub' )}}"
  delegate_to: "{{ item }}"
  run_once: true
  loop: "{{groups['worker']}}"
```

これは`run_once: true`が無いと、(taskのターゲットホストの)`all`の1ホスト毎に`loop`によるworkerノードの処理が実行される。
